# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NOverdose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nopioids
  pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v0.17.0-beta.1'
  pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v0.17.0-beta.1'
  
end
